
services:
  app:
    # container_name: onboarding_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=local
    volumes:
      - ./key.json:/src/key.json:ro
      - ./src:/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - onboarding-network

networks:
  onboarding-network:
    driver: bridge
  monthly_postgres:
    external: true

volumes:
  app-data:
